apiVersion: v1
kind: Service
metadata:
  name: simpletracking-loadbalancer
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    app: simpletracking
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simpletracking
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: simpletracking
      app: simpletracking
  template:
    metadata:
      labels:
        k8s-app: simpletracking
        app: simpletracking
      name: simpletracking
    spec:
      containers:
      - image: ytechie/simpletracking
        imagePullPolicy: Always
        name: simpletracking
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
