apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletracking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpletracking
  template:
    metadata:
      labels:
        app: simpletracking
    spec:
      containers:
      - image: ytechie/simpletracking
        name: simpletracking
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: simpletracking-loadbalancer
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3080
  type: LoadBalancer
  selector:
    app: simpletracking