name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm run build --if-present
    - name: Spit out version file
      run: echo "`date -u`" > src/when.txt
    - name: Set up Docker Buildx
      run: docker build -t ytechie/simpletracking .
    - name: Export container
      run: docker save ytechie/simpletracking:latest > st-image.tar
    - name: Save Docker image as artifact
      uses: actions/upload-artifact@master
      with:
        name: image-file
        path: st-image.tar

  deploy-docker-hub:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Load Docker image artifact
        uses: actions/download-artifact@master
        with:
          name: image-file
          path: st-image.tar
      - name: Load Docker image
        run: docker load --input st-image.tar
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_password }}
